#!/usr/bin/env bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#

if ! grep  --only-matching amulet <<< $I &> /dev/null; then
    cat << EOF
You have found an emerald **amulet**!

To collect treasure, you must have a variable to hold your inventory.

Create a variable and add your treasure to it like this:

export I=amulet,\$I

You can always check your wealth with this command:

echo \$I

EOF
    if [ -d ../.chapel ] || [ -d ../.vault ] || [ -d ../.scrap ]; then
        echo ""
        echo "You hear stone grinding in the distance..."
        echo "New passages have opened in the entrance above!"
        echo "Return to the entrance and look around with: ls"
        echo ""
    fi
    mv ../.chapel ../chapel 2>/dev/null
    mv ../.vault ../vault 2>/dev/null
    mv ../.scrap ../scrap 2>/dev/null
else
    echo "This treasure has already been taken."
fi



# ========================================================================
# If you are seeing this, you used 'cat' to read an executable file.
# That is great curiosity! But to USE this item, run it with:
#
#     ./treasure
#
# Files marked with * in 'ls -F' output are executables (programs).
# The ./ prefix means "run the file right here in this directory."
# ========================================================================
