"use strict";
// Golden-transcript scenarios: the pixel-identity contract for the game
// runtime. Each scenario pins its own rng seed (and shares the fixed fixture
// clock), so every recorded output — including fortune draws, arena shuffles
// and pathfind targets — replays byte-identically.
//
// Regenerate fixtures ONLY with:  node termforge/test/tools/record-goldens.js --update
// A fixture diff in review is a claimed behavior change of the game runtime.

const SCENARIOS = [
    {
        name: "posix-basics",
        seed: 101,
        steps: [
            "pwd",
            "ls",
            "ls -a",
            "ls -F",
            "cat scroll",
            "file scroll",
            "cd cellar",
            "ls -F",
            "cat scroll",
            "cd ..",
            "pwd",
            "tree",
            "find . -name scroll",
            "find . -type d",
            "grep -r amulet .",
            "echo hello adventurer",
            "export TORCH=lit",
            "echo $TORCH",
            "env",
            "alias ll='ls -F'",
            "ll",
            "alias",
            "whoami",
            "man ls",
            "man map",
            "man nosuchcmd",
            "date",
            "cd -",
            "pwd",
            "cd nowhere",
            "cat nofile",
            "frobnicate",
        ],
    },
    {
        name: "pipes-and-files",
        seed: 202,
        steps: [
            "cat scroll | wc -l",
            "cat scroll | head -3",
            "cat scroll | head -3 | tail -1",
            "head -n 2 scroll",
            "tail -2 scroll",
            "echo cherry > fruit",
            "echo apple >> fruit",
            "echo banana >> fruit",
            "echo apple >> fruit",
            "cat fruit",
            "sort fruit",
            "sort fruit | uniq",
            "sort fruit | uniq -c",
            "sort fruit | uniq -d",
            "cat fruit | rev",
            "cat fruit | nl",
            "cat fruit | tr a-z A-Z",
            "cat fruit | sed 's/apple/mango/'",
            "echo a,b,c | cut -d, -f2",
            "echo abcdef | cut -c2-4",
            "cat scroll | wc -l > count",
            "cat count",
            "echo quiet 2>/dev/null",
            "cat scroll 2>&1 | wc -l",
            "echo broken >",
            "echo broken > f g",
            "cat scroll > scroll",
            "cat scroll | head -1",
            "rm scroll",
            "cat scroll | head -1",
            "rm scroll",
            "mkdir camp",
            "touch camp/log",
            "cp fruit camp/fruit2",
            "mv camp/fruit2 camp/fruit3",
            "ls camp",
            "rm camp/fruit3",
            "ls camp",
            "touch torch",
            "chmod +x torch",
            "ls -F",
            "chmod -x torch",
            "chmod 755 torch",
            "chmod +x scroll",
            "grep 'ls -a' scroll",
            "grep -c the scroll",
            "grep -n Bashcrawl scroll",
            "ls c*",
            "cat 'fru*'",
            "clear",
        ],
    },
    {
        name: "main-quest-run",
        seed: 303,
        steps: [
            "pwd",
            "ls",
            "cd cellar",
            "cat scroll",
            "./treasure",
            "inventory",
            "echo $I",
            "./treasure",
            "cd armoury",
            "./treasure",
            "./potion",
            "grep sword scroll",
            "cd chamber",
            "./treasure",
            "./statue",
            "health",
            "status",
            "mkdir workshop",
            "touch workshop/anvil",
            "cd /entrance",
            "ls",
            "map",
            "cd chapel",
            "ls -F",
            "look",
            "cd graveyard",
            "ls",
            "./padlock",
            "ls",
            "cd mausoleum",
            "pwd",
            "cd /entrance/vault",
            "ls -F",
            "cd stronghold",
            "./goblet",
            "cd /entrance",
            "ls",
            "cd rift",
            "pwd",
            "cd /entrance",
            "cd cellar",
            "grep amulet scroll",
            "cd /entrance",
            "mkdir study",
            "cd study",
            "touch grimoire",
            "source grimoire",
            "bc",
            "cd /entrance",
            "quest",
            "hint",
            "xp",
            "profile",
            "achievements",
            "bestiary",
            "bestiary treasure",
            "daily",
            "save",
            "save export",
        ],
    },
    {
        name: "trainer-arena",
        seed: 404,
        steps: [
            "train",
            "hint",
            "skip",
            "blargh",
            "blargh",
            "quit",
            "speedrun",
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            { line: "skip", advanceMs: 1500 },
            "speedrun",
            "quit",
            "train",
            "ls",
            "pwd",
            "quit",
            "xp",
        ],
    },
    {
        name: "meta-and-flavour",
        seed: 505,
        steps: [
            "fortune",
            "fortune",
            "cowsay hello dungeon",
            "cowsay",
            "echo moo | cowsay",
            "figlet",
            "figlet rune",
            "banner",
            "sl",
            "bestiary",
            "bestiary treasure",
            "bestiary dragon",
            "commands",
            "daily",
            "let HP=HP-5",
            "health",
            "let HP=HP+5",
            "source scroll",
            "pathfind",
            "pathfind",
            "cd cellar",
            "cd armoury",
            "cd chamber",
            "pathfind quit",
            "pathfind",
            "pathfind quit",
            "help",
            "reset",
            "pwd",
            "quest",
            { line: "daily", advanceMs: 86400000 },
        ],
    },
];

module.exports = { SCENARIOS };
