#!/usr/bin/env python3
"""Scaffold a new room and optional encounter from shared contracts."""

from __future__ import annotations

import argparse
import stat
from pathlib import Path
from typing import Any

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--room-key", required=True, help="rooms.yaml key (e.g. observatory)")
    parser.add_argument(
        "--room-path",
        required=True,
        help="Path under entrance/ using logical naming (e.g. entrance/cellar/observatory)",
    )
    parser.add_argument("--title", required=True, help="Room title")
    parser.add_argument("--emoji", default="🗺️", help="Room emoji")
    parser.add_argument("--prompt-label", default="exploring", help="Prompt label")
    parser.add_argument("--hint", default="", help="Room context hint")
    parser.add_argument("--description", default="", help="Room description")
    parser.add_argument("--encounter-key", default="", help="Optional encounter key")
    parser.add_argument("--encounter-script", default="", help="Optional encounter script filename")
    parser.add_argument("--encounter-type", default="puzzle", help="Optional encounter type")
    parser.add_argument(
        "--apply-metadata",
        action="store_true",
        help="Apply entries directly to rooms.yaml/encounters.yaml",
    )
    return parser.parse_args()


def _to_disk_path(logical_path: str) -> str:
    parts = [p for p in logical_path.strip("/").split("/") if p]
    return "/".join(parts)


def _write_scroll(room_dir: Path, title: str, hint: str) -> None:
    scroll = room_dir / "scroll"
    if scroll.exists():
        return
    body = [
        title,
        "",
        "New room scaffold generated by scripts/scaffold_content.py.",
        "",
        "Next steps:",
        "- Fill this scroll with gameplay context and command guidance.",
        "- Add encounter scripts and update walkthrough metadata.",
    ]
    if hint:
        body.extend(["", f"Hint: {hint}"])
    scroll.write_text("\n".join(body) + "\n", encoding="utf-8")


def _write_encounter(room_dir: Path, script_name: str) -> Path:
    script = room_dir / script_name
    if script.exists():
        return script
    script.write_text(
        "#!/usr/bin/env bash\n"
        "\n"
        "echo \"This encounter is a scaffold. Replace with game logic.\"\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return script


def _load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a top-level object")
    return data


def _save_yaml(path: Path, payload: dict[str, Any]) -> None:
    text = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    path.write_text(text, encoding="utf-8")


def _upsert_room_metadata(root: Path, args: argparse.Namespace) -> None:
    path = root / "src/help/data/rooms.yaml"
    data = _load_yaml(path)
    rooms = data.setdefault("rooms", {})
    if not isinstance(rooms, dict):
        raise ValueError("rooms.yaml 'rooms' must be an object")

    rooms[args.room_key] = {
        "emoji": args.emoji,
        "title": args.title,
        "path": args.room_path,
        "prompt_label": args.prompt_label,
        "context_hint": args.hint,
        "hidden": False,
        "unlocked_by": None,
        "parent": None,
        "children": [],
        "on_enter": None,
        "on_exit": None,
        "description": args.description or "Scaffolded room",
        "teaches": [],
        "key_files": [{"name": "scroll", "description": "documentation"}],
        "next_steps": "Fill in room guidance and encounters",
        "essential_commands": [{"command": "cat scroll", "description": "Read the room guide"}],
    }
    _save_yaml(path, data)


def _upsert_encounter_metadata(root: Path, args: argparse.Namespace) -> None:
    if not args.encounter_key or not args.encounter_script:
        return
    path = root / "src/help/data/encounters.yaml"
    data = _load_yaml(path)
    encounters = data.setdefault("encounters", {})
    if not isinstance(encounters, dict):
        raise ValueError("encounters.yaml 'encounters' must be an object")
    encounters[args.encounter_key] = {
        "script": args.encounter_script,
        "room": args.room_key,
        "type": args.encounter_type,
        "description": "Scaffolded encounter",
        "icon": "⚡",
        "requires_items": [],
        "recommended_items": [],
        "grants_items": [],
        "unlocks_rooms": [],
        "damage": 0,
    }
    _save_yaml(path, data)


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parent.parent
    room_rel = _to_disk_path(args.room_path)
    room_dir = root / room_rel
    room_dir.mkdir(parents=True, exist_ok=True)
    _write_scroll(room_dir, args.title, args.hint)

    if args.encounter_script:
        _write_encounter(room_dir, args.encounter_script)

    if args.apply_metadata:
        _upsert_room_metadata(root, args)
        _upsert_encounter_metadata(root, args)
        print("✅ Scaffolded content and updated YAML metadata.")
    else:
        print("✅ Scaffolded room files.")
        print("Run again with --apply-metadata to update rooms.yaml / encounters.yaml.")
    print(f"Room directory: {room_dir.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
