#!/usr/bin/env bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
if [ -e drum ]; then
    cat << EOF
War drums pound in the distance, giving Nyarlathotep
strength.

If you know a spell to un-summon the drums, Nyarlathotep
would probably weaken! If you know how to look up a new
command, learn the "mv" command now.

EOF
else
    cat << EOF
The drumming has stopped.  Now is your chance to attack!

EOF
fi



# ========================================================================
# If you are seeing this, you used 'cat' to read an executable file.
# That is great curiosity! But to USE this item, run it with:
#
#     ./drummer
#
# Files marked with * in 'ls -F' output are executables (programs).
# The ./ prefix means "run the file right here in this directory."
# ========================================================================
