#!/usr/bin/env bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
if ! grep  --quiet --only-matching hair <<< $I; then
    cat << eof
You have found a lock of the **hair** of a god!  Add it to your inventory.

eof
else
    echo "This treasure has already been taken."
fi

