#!/usr/bin/env bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
if [ -e wizard-dark ]; then
    cat << EOF
The ancient wizard, Arnnisen the Gray, takes form before
your very eyes. You have freed him, and now he fights by
your side against the crawling chaos!

EOF
else
    cat << EOF
You feel a presence.  It's probably just your imagination.

EOF
fi



# ========================================================================
# If you are seeing this, you used 'cat' to read an executable file.
# That is great curiosity! But to USE this item, run it with:
#
#     ./wizard-light
#
# Files marked with * in 'ls -F' output are executables (programs).
# The ./ prefix means "run the file right here in this directory."
# ========================================================================
